# Generated by Django 5.0.6 on 2024-10-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_tutor_hours_per_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutor",
            name="days_of_week",
        ),
        migrations.AddField(
            model_name="tutor",
            name="friday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="friday_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="monday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="monday_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="thursday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="thursday_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="tuesday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="tuesday_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="wednesday_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="wednesday_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
